[package]
name = "fish-game"
version = "0.1.0"
authors = ["Nigel Haney <nigel.haney27@gmail.com>"]
edition = "2018"

[features]
# bevy features
default = [
  "bevy/bevy_gltf",
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png",
  "bevy/bevy_audio",
  "bevy/vorbis",
]

# different rendering for native vs. web, no official bevy support
native = [
  "bevy/bevy_wgpu",
]

web = [
  "bevy_webgl2"
]

[dependencies]
bevy = {git = "https://github.com/bevyengine/bevy", branch="master", default-features=false}
bevy_webgl2 = {git = "https://github.com/mrk-its/bevy_webgl2", branch="master", optional=true}
bevy_prototype_lyon = { git = "https://github.com/nhaney/bevy_prototype_lyon", branch = "master"}

rand = { version = "0.7", default-features = false }
rand_chacha = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2.69"

# depedencies of bevy that need features enabled for web builds
[dependencies.web-sys]
version = "0.3.4"
features = [
  'Storage',
  'Window',
]

[dependencies.rodio]
git = "https://github.com/RustAudio/rodio"
branch = "master"
features = [
    'vorbis',
    'wasm-bindgen'
]
default-features = false

[dependencies.winit]
version = "0.24.0"
features = ["web-sys", "x11"]
default-features = false


[profile.dev]
opt-level = 1

[profile.release]
lto = true
opt-level = 's'
