[package]
name = "fish-game"
version = "0.1.0"
authors = ["Nigel Haney <nigel.haney27@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "master" }
bevy_prototype_lyon = { git = "https://github.com/nhaney/bevy_prototype_lyon", branch = "master" }
rand = { version = "0.7", default-features = false }
rand_chacha = "0.2.2"
