[package]
name = "fish-game"
version = "0.1.0"
authors = ["Nigel Haney <nigel.haney27@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = [
  "bevy/bevy_gltf",
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png",
]

native = [
  "bevy/bevy_wgpu",
]

web = [
  "bevy_webgl2"
]

[dependencies]
bevy = {git = "https://github.com/bevyengine/bevy", default-features=false}
bevy_webgl2 = {git = "https://github.com/mrk-its/bevy_webgl2", optional=true}
winit = {version = "0.23.0", features = ["web-sys", "x11"], default-features = false}

rand = { version = "0.7", default-features = false }
rand_chacha = "0.2.2"
bevy_prototype_lyon = { git = "https://github.com/Vrixyz/bevy_prototype_lyon", branch = "master" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

wasm-bindgen = "0.2.69"

[patch.'https://github.com/bevyengine/bevy']
bevy = {git = "https://github.com/bevyengine/bevy//", branch="master", default-features=false}

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Storage',
  'Window',
]

[profile.dev]
opt-level = 1

[profile.release]
lto = true
opt-level = 's'
