# runs quality checks and, if successful, uploads an artifact of the built wasm and native games
name: CI
on: [push]

on: [push]
jobs:
  build-and-publish-linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          # Mostly to avoid GitHub rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build game
        run: nix build .
      - name: Upload to github artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stay-off-the-line-remastered-${{ runner.os }}-release-${{ github.sha }}
          path: result/bin/
  build-and-publish-wasm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          # Mostly to avoid GitHub rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build game
        run: "nix build .#wasm"
      - name: Upload to github artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stay-off-the-line-remastered-wasm-release-${{ github.sha }}
          path: result/bin/
