# Runs nix build to build both the WASM build of the game and uploads it to github artifacts.
# TODO: Add in a linux build with statically linked nix and a windows build with normal cargo actions.
on: [push]
jobs:
  build-and-publish-wasm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          # Mostly to avoid GitHub rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build game
        run: "nix build .#wasm"
      - name: Upload to github artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stay-off-the-line-remastered-wasm-release-${{ github.sha }}
          path: result/bin/

